name: "Sync to Cloudflare R2"

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Upload to R2
        run: aws s3 sync ./public/ s3://covid-19 --acl public-read
        env:
          AWS_ENDPOINT_URL: https://078fcdfed9955087315dd86792e71a7e.r2.cloudflarestorage.com
          AWS_DEFAULT_REGION: auto # this is necessary for some reason!
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
